In [3]:
import pandas as pd
from get_path import get_path as gp

In [4]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif, chi2
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [5]:
df = pd.read_csv(gp(bins = True))

In [6]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,radius error
0,"(11.207, 13.32]","(21.538, 24.495]","(87.203, 101.674]","(379.25, 615.0]","(0.119, 0.13]","(0.182, 0.215]","(0.171, 0.213]","(0.0805, 0.101]","(0.217, 0.235]","(0.0737, 0.0784]",0.3063
1,"(19.658, 21.771]","(21.538, 24.495]","(116.145, 130.616]","(1086.5, 1322.25]","(0.0969, 0.108]","(0.0846, 0.117]","(0.128, 0.171]","(0.0805, 0.101]","(0.143, 0.161]","(0.0499, 0.0547]",0.7582
2,"(11.207, 13.32]","(15.624, 18.581]","(72.732, 87.203]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0427, 0.0854]","(0.0201, 0.0402]","(0.18, 0.198]","(0.0642, 0.069]",0.1852
3,"(9.094, 11.207]","(9.68, 12.667]","(58.261, 72.732]","(141.142, 379.25]","(0.0969, 0.108]","(0.052, 0.0846]","(-0.000427, 0.0427]","(0.0201, 0.0402]","(0.18, 0.198]","(0.069, 0.0737]",0.2773
4,"(13.32, 15.433]","(18.581, 21.538]","(87.203, 101.674]","(379.25, 615.0]","(0.0969, 0.108]","(0.117, 0.15]","(0.0854, 0.128]","(0.0402, 0.0604]","(0.161, 0.18]","(0.0595, 0.0642]",0.2130


In [7]:
df["radius error"] = pd.cut(df['radius error'], 10)

In [8]:
x = df.iloc[:, :10]
y = df.iloc[:, -1]

In [9]:
x = OrdinalEncoder().fit_transform(x)
y = LabelEncoder().fit_transform(y)

In [10]:
x

array([[0., 3., 5., 2., 5., 5., 4., 4., 5., 5.],
       [4., 3., 1., 0., 3., 2., 3., 4., 1., 0.],
       [0., 1., 4., 2., 3., 3., 1., 1., 3., 3.],
       [5., 7., 3., 1., 3., 1., 0., 1., 3., 4.],
       [1., 2., 5., 2., 3., 3., 2., 2., 2., 2.],
       [0., 2., 5., 2., 3., 3., 2., 3., 3., 3.],
       [0., 2., 4., 2., 1., 0., 0., 0., 3., 1.],
       [5., 0., 3., 1., 1., 2., 1., 1., 5., 4.],
       [0., 3., 4., 2., 4., 3., 2., 3., 3., 3.],
       [0., 0., 5., 2., 6., 4., 4., 4., 3., 5.],
       [1., 1., 5., 3., 4., 4., 2., 4., 4., 3.],
       [3., 3., 1., 4., 2., 2., 2., 3., 2., 1.],
       [0., 1., 4., 2., 4., 4., 3., 3., 7., 5.],
       [0., 0., 4., 2., 2., 1., 0., 0., 1., 1.],
       [5., 7., 3., 1., 2., 1., 0., 0., 0., 2.],
       [5., 0., 3., 1., 2., 0., 0., 0., 2., 2.],
       [1., 1., 5., 3., 2., 2., 1., 2., 1., 2.],
       [0., 1., 4., 2., 2., 1., 0., 1., 3., 1.],
       [2., 1., 0., 4., 3., 2., 2., 4., 3., 1.],
       [3., 2., 1., 0., 2., 1., 1., 2., 1., 0.],
       [0., 0., 4., 

In [11]:
y

array([1, 6, 0, 1, 0, 2, 2, 2, 2, 2, 2, 4, 1, 0, 0, 2, 1, 2, 1, 1, 4, 0,
       8, 2, 0, 0, 3, 0, 0, 0, 0, 2, 1, 0, 2, 1, 7, 2, 1, 0, 2, 0, 5, 2])

# **Mutual information**

In [16]:
selector = SelectKBest(lambda x, y: mutual_info_classif(x, y, discrete_features = True), k = 5)

In [17]:
selector.fit_transform(x, y)

array([[0., 5., 4., 4., 5.],
       [4., 2., 3., 4., 1.],
       [0., 3., 1., 1., 3.],
       [5., 1., 0., 1., 3.],
       [1., 3., 2., 2., 2.],
       [0., 3., 2., 3., 3.],
       [0., 0., 0., 0., 3.],
       [5., 2., 1., 1., 5.],
       [0., 3., 2., 3., 3.],
       [0., 4., 4., 4., 3.],
       [1., 4., 2., 4., 4.],
       [3., 2., 2., 3., 2.],
       [0., 4., 3., 3., 7.],
       [0., 1., 0., 0., 1.],
       [5., 1., 0., 0., 0.],
       [5., 0., 0., 0., 2.],
       [1., 2., 1., 2., 1.],
       [0., 1., 0., 1., 3.],
       [2., 2., 2., 4., 3.],
       [3., 1., 1., 2., 1.],
       [0., 0., 0., 1., 4.],
       [5., 0., 0., 0., 1.],
       [3., 4., 5., 5., 2.],
       [0., 2., 1., 1., 2.],
       [0., 0., 0., 0., 1.],
       [0., 2., 0., 1., 2.],
       [2., 6., 6., 6., 6.],
       [1., 1., 0., 1., 3.],
       [1., 0., 0., 0., 0.],
       [5., 1., 0., 0., 3.],
       [1., 2., 2., 2., 3.],
       [5., 1., 1., 1., 1.],
       [5., 1., 0., 0., 4.],
       [1., 6., 6., 4., 4.],
       [3., 3.

In [18]:
import numpy as np
df.columns[np.append(selector.get_support(), False)]

Index(['mean radius', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry'],
      dtype='str')

# **Chi-square**

In [14]:
selector = SelectKBest(chi2, k = 5)

In [19]:
selector.fit_transform(x, y)

array([[0., 5., 4., 4., 5.],
       [4., 2., 3., 4., 1.],
       [0., 3., 1., 1., 3.],
       [5., 1., 0., 1., 3.],
       [1., 3., 2., 2., 2.],
       [0., 3., 2., 3., 3.],
       [0., 0., 0., 0., 3.],
       [5., 2., 1., 1., 5.],
       [0., 3., 2., 3., 3.],
       [0., 4., 4., 4., 3.],
       [1., 4., 2., 4., 4.],
       [3., 2., 2., 3., 2.],
       [0., 4., 3., 3., 7.],
       [0., 1., 0., 0., 1.],
       [5., 1., 0., 0., 0.],
       [5., 0., 0., 0., 2.],
       [1., 2., 1., 2., 1.],
       [0., 1., 0., 1., 3.],
       [2., 2., 2., 4., 3.],
       [3., 1., 1., 2., 1.],
       [0., 0., 0., 1., 4.],
       [5., 0., 0., 0., 1.],
       [3., 4., 5., 5., 2.],
       [0., 2., 1., 1., 2.],
       [0., 0., 0., 0., 1.],
       [0., 2., 0., 1., 2.],
       [2., 6., 6., 6., 6.],
       [1., 1., 0., 1., 3.],
       [1., 0., 0., 0., 0.],
       [5., 1., 0., 0., 3.],
       [1., 2., 2., 2., 3.],
       [5., 1., 1., 1., 1.],
       [5., 1., 0., 0., 4.],
       [1., 6., 6., 4., 4.],
       [3., 3.

In [20]:
df.columns[np.append(selector.get_support(), False)]

Index(['mean radius', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry'],
      dtype='str')