In [1]:
from sklearn.preprocessing import KBinsDiscretizer

In [2]:
import pandas as pd
from get_path import get_path as gp

In [3]:
df = pd.read_csv(gp()).iloc[:, :5].dropna()

In [4]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness
2,19.69,21.25,130.00,1203.0,0.10960
3,11.42,20.38,77.58,386.1,0.14250
8,13.00,21.82,87.50,519.8,0.12730
13,15.85,23.95,103.70,782.7,0.08401
14,13.73,22.61,93.60,578.3,0.11310


# **Bins of uniform width**

In [ ]:
binner = KBinsDiscretizer(strategy="uniform", n_bins=5)

In [8]:
binner.fit_transform(df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 880 stored elements and shape (176, 25)>

In [9]:
binner = KBinsDiscretizer(strategy="uniform", n_bins=5, encode="onehot-dense")

In [10]:
binner.fit_transform(df)

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(176, 25))

# **Binning using quantiles**    

In [15]:
binner = KBinsDiscretizer(strategy="quantile", n_bins = 3, encode = "ordinal")

In [16]:
t = binner.fit_transform(df)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/preprocessing/_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(


### **Do note that the difference between `uniform` and `quantile`, is that:**
- Uniform: divides the range into n_bins, i.e., if range of values is 10 -> 110, and number of bins is 5, then the number of elements in each bin range = (110-10) / 5 = 20. This means that 10 -> 30, 1st bin, 30 -> 50, 2nd bin, etc... notice that number of elements in each bin may vary drastically.
- Quantile: divides the data into n_bins such that each bin has approximately same, m number of elements. This means that if range of values from 10 -> 110, and number of bins = 4, but our dataset only has [1, 2, 3, 4, 5, 60, 23, 110], then, each bin becomes -> [1, 2], [3, 4], [5, 23], [60, 110]. Notice that though number of elements are roughly the same, the value of the elements in that bin varies drastically

In [17]:
import numpy as np
np.unique(t[:, 0] ,return_counts=True)

(array([0., 1., 2.]), array([59, 58, 59]))

# **Binning using K-means**

In [18]:
binner = KBinsDiscretizer(strategy="kmeans", n_bins = 3, encode = "ordinal")

In [21]:
(t := binner.fit_transform(df))

array([[1., 1., 2., 1., 1.],
       [0., 1., 0., 0., 2.],
       [0., 1., 0., 0., 2.],
       [1., 2., 1., 0., 0.],
       [0., 1., 1., 0., 2.],
       [1., 1., 2., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 2.],
       [0., 1., 1., 0., 1.],
       [1., 2., 1., 1., 2.],
       [1., 2., 2., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [1., 2., 2., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 2., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 2., 1., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 2.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 2.],
       [1., 2., 2., 1., 2.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 2.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 2.],
       [1., 0., 2., 1., 1.],
       [1., 1., 2., 1., 0.],
       [0., 0.