In [31]:
from sklearn.naive_bayes import CategoricalNB

In [32]:
from sklearn.datasets import load_iris

In [33]:
from sklearn.preprocessing import KBinsDiscretizer #numerical -> categorical

In [34]:
x, y = load_iris(return_X_y=True)

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.4,
    random_state=11
)

In [36]:
transformer = KBinsDiscretizer(strategy="uniform", n_bins=5, encode="ordinal")

In [37]:
transformer.fit(x_train)

,"n_bins n_bins: int or array-like of shape (n_features,), default=5The number of bins to produce. Raises ValueError if ``n_bins < 2``.",5
,"encode encode: {'onehot', 'onehot-dense', 'ordinal'}, default='onehot'Method used to encode the transformed result.- 'onehot': Encode the transformed result with one-hot encoding and return a sparse matrix. Ignored features are always stacked to the right.- 'onehot-dense': Encode the transformed result with one-hot encoding and return a dense array. Ignored features are always stacked to the right.- 'ordinal': Return the bin identifier encoded as an integer value.",'ordinal'
,"strategy strategy: {'uniform', 'quantile', 'kmeans'}, default='quantile'Strategy used to define the widths of the bins.- 'uniform': All bins in each feature have identical widths.- 'quantile': All bins in each feature have the same number of points.- 'kmeans': Values in each bin have the same nearest center of a 1D k-means cluster.For an example of the different strategies see::ref:`sphx_glr_auto_examples_preprocessing_plot_discretization_strategies.py`.",'uniform'
,"quantile_method quantile_method: {""inverted_cdf"", ""averaged_inverted_cdf"",""closest_observation"", ""interpolated_inverted_cdf"", ""hazen"",""weibull"", ""linear"", ""median_unbiased"", ""normal_unbiased""},default=""linear""Method to pass on to np.percentile calculation when usingstrategy=""quantile"". Only `averaged_inverted_cdf` and `inverted_cdf`support the use of `sample_weight != None` when subsampling is notactive... versionadded:: 1.7",'warn'
,"dtype dtype: {np.float32, np.float64}, default=NoneThe desired data-type for the output. If None, output dtype isconsistent with input dtype. Only np.float32 and np.float64 aresupported... versionadded:: 0.24",None
,"subsample subsample: int or None, default=200_000Maximum number of samples, used to fit the model, for computationalefficiency.`subsample=None` means that all the training samples are used whencomputing the quantiles that determine the binning thresholds.Since quantile computation relies on sorting each column of `X` andthat sorting has an `n log(n)` time complexity,it is recommended to use subsampling on datasets with avery large number of samples... versionchanged:: 1.3 The default value of `subsample` changed from `None` to `200_000` when `strategy=""quantile""`... versionchanged:: 1.5 The default value of `subsample` changed from `None` to `200_000` when `strategy=""uniform""` or `strategy=""kmeans""`.",200000
,"random_state random_state: int, RandomState instance or None, default=NoneDetermines random number generation for subsampling.Pass an int for reproducible results across multiple function calls.See the `subsample` parameter for more details.See :term:`Glossary `... versionadded:: 1.1",None


In [38]:
x_test_categ = transformer.transform(x_test)
x_train_categ = transformer.transform(x_train)

In [39]:
x_test_categ

array([[3., 2., 3., 4.],
       [3., 2., 3., 4.],
       [2., 1., 3., 2.],
       [2., 2., 3., 3.],
       [3., 1., 3., 3.],
       [0., 2., 0., 0.],
       [3., 2., 2., 2.],
       [2., 4., 0., 0.],
       [0., 2., 0., 0.],
       [2., 1., 3., 2.],
       [2., 0., 3., 2.],
       [2., 0., 2., 1.],
       [1., 2., 3., 2.],
       [2., 0., 3., 3.],
       [3., 2., 3., 4.],
       [0., 0., 0., 0.],
       [2., 1., 4., 3.],
       [1., 2., 3., 2.],
       [3., 2., 3., 3.],
       [2., 1., 3., 3.],
       [1., 0., 2., 2.],
       [0., 2., 0., 0.],
       [0., 3., 0., 0.],
       [3., 2., 3., 2.],
       [0., 2., 0., 0.],
       [0., 2., 0., 0.],
       [2., 2., 3., 3.],
       [3., 2., 2., 2.],
       [1., 4., 0., 0.],
       [2., 2., 3., 3.],
       [1., 3., 0., 0.],
       [3., 2., 4., 4.],
       [4., 1., 4., 3.],
       [1., 2., 0., 0.],
       [0., 2., 0., 0.],
       [4., 1., 4., 4.],
       [4., 2., 4., 4.],
       [3., 2., 3., 3.],
       [1., 3., 0., 0.],
       [2., 1., 3., 3.],


In [40]:
model = CategoricalNB()

In [41]:
model.fit(x_train_categ, y_train)

,"alpha alpha: float, default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"min_categories min_categories: int or array-like of shape (n_features,), default=NoneMinimum number of categories per feature.- integer: Sets the minimum number of categories per feature to `n_categories` for each features.- array-like: shape (n_features,) where `n_categories[i]` holds the minimum number of categories for the ith column of the input.- None (default): Determines the number of categories automatically from the training data... versionadded:: 0.24",None


In [42]:
model.predict(x_test_categ)

array([2, 2, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 1,
       2, 1, 1, 0, 2, 0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 0])

In [43]:
model.predict_proba(x_test_categ)

array([[3.49939987e-04, 5.16911468e-03, 9.94480945e-01],
       [3.49939987e-04, 5.16911468e-03, 9.94480945e-01],
       [7.36875351e-05, 9.55132780e-01, 4.47935320e-02],
       [9.27025959e-04, 4.10805024e-02, 9.57992472e-01],
       [7.57384214e-05, 5.03444220e-02, 9.49579840e-01],
       [9.99807582e-01, 7.21827448e-05, 1.20235221e-04],
       [1.19819955e-03, 9.66372114e-01, 3.24296862e-02],
       [9.97879491e-01, 1.18871846e-03, 9.31790734e-04],
       [9.99807582e-01, 7.21827448e-05, 1.20235221e-04],
       [7.36875351e-05, 9.55132780e-01, 4.47935320e-02],
       [6.77145403e-05, 9.75234702e-01, 2.46975836e-02],
       [2.85937821e-04, 9.97851734e-01, 1.86232771e-03],
       [1.66076514e-02, 9.23173346e-01, 6.02190030e-02],
       [2.60122744e-04, 2.88178905e-01, 7.11560973e-01],
       [3.49939987e-04, 5.16911468e-03, 9.94480945e-01],
       [9.97881252e-01, 1.80109176e-03, 3.17656493e-04],
       [1.77405594e-04, 1.76886089e-02, 9.82133985e-01],
       [1.66076514e-02, 9.23173