In [2]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
import numpy as np

# Exercise 1

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to all variables
* Apply One-hot encoding to the first column and ordinal encoding to the second column following the rank Low, Medium, High

In [15]:
x  = [["X","High"],
      ["Y","Low"],
      ["Z","Medium"],
      ["X","Low"]]


In [29]:
enc = ColumnTransformer([
    ("one_hot_encoder", OneHotEncoder(), [0, 1])
])

In [30]:
enc.fit_transform(x)

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [33]:
enc = ColumnTransformer([
    ("one_hot", OneHotEncoder(), [0]),
    ("ordinal", OrdinalEncoder(categories=[["Low", "Medium", "High"]]), [1])
])

In [34]:
enc.fit_transform(x)

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.]])

# Exercise 2

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to the first variable and ordinal encoding to the second variable. 
  * The first variable must be encoded considering this set of values: X, Y, Z, W. 
  * The second variable must be encoded considering this set of ranked values: Low, Medium, High, Very high
* Consider the dataset:
```python
Y = [["W","Very high"]]
```
* Transform this dataset according to the fitted encoder

In [35]:
x = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]

In [36]:
enc = ColumnTransformer([
    ("one_hot", OneHotEncoder(categories=[["X", "Y", "Z", "W"]]), [0]),
    ("ordinal", OrdinalEncoder(categories=[["Low", "Medium", "High", "Very high"]]), [1])
])

In [37]:
enc.fit_transform(x)

array([[1., 0., 0., 0., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [40]:
y = [["W","Very high"]]

In [41]:
enc.transform(y)

array([[0., 0., 0., 1., 3.]])