In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
x = np.array([["A"],
              ["A"],
              ["B"],
              ["C"]]) #table with only one categorical feature and four records -> A A B C

In [3]:
x

array([['A'],
       ['A'],
       ['B'],
       ['C']], dtype='<U1')

In [4]:
enc = OneHotEncoder()

In [5]:
enc.fit_transform(x).todense() #gives sparse matrix, converting to dense

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### Each column in this matrix is called a **"Dummy variable"**
- ### The dummy variale is  either 0 or 1, 0 indicating a false value and 1 indicating a true value
- ### The first dummy variable asks "is this 'A'?" So the dummy variable for A for the first two entries is 1, i.e., true.
- ### The second, is for 'B'. Asks the same question. Hence the first two entries show 0 for this column while the third shows 1.
- ### Same functioning but for C for the third dummy variable

# Output with dense matrix

In [6]:
enc = OneHotEncoder(sparse_output=False)

In [7]:
enc.fit_transform(x)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Removing one variable -> k-1 dummies**
### As all of the features when encoding with k dummies add up to 1, they become linearly dependent, which is bad for linear models. They require indepent features. Hence, we drop the first dummy, i.e., we use k-1 dummies.

In [8]:
enc = OneHotEncoder(sparse_output=False, drop='first')

In [9]:
enc.fit_transform(x)

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

# **Drop if binary**
### Drops the first dummy if only 2 dummies exist
### Raises error if more than 2 dummies are present.

In [10]:
x = np.array([["A"],
              ["C"],
              ["A"],
              ["A"]]) #only 2 dummies

In [11]:
enc = OneHotEncoder(sparse_output = False, drop="if_binary")

In [13]:
enc.fit_transform(x)

array([[0.],
       [1.],
       [0.],
       [0.]])

In [19]:
y = np.array([["A"],
              ["A"],
              ["B"],
              ["C"]])

In [20]:
enc = OneHotEncoder(sparse_output = False, drop="if_binary")

In [ ]:
enc.fit_transform(y) 

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### No dummies were dropped

# ***Handling errors***

In [22]:
enc = OneHotEncoder(sparse_output=False, drop = "if_binary")

In [23]:
enc.fit(x) # learns x, only knows about A and C

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",'if_binary'
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a :class:`scipy.sparse.csr_matrix`,i.e. a sparse matrix in ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide `.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide `.",None
,"ma

In [24]:
enc.transform(y) # does not know about B, raises error

ValueError: Found unknown categories [np.str_('B')] in column 0 during transform

### We can handle this error by using the **`handle_unknown`** parameter.
### Setting it to **`ignore`** makes the encoder fill 0 on known dummies for an unknown value.

In [25]:
enc = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

In [26]:
enc.fit(x)

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a :class:`scipy.sparse.csr_matrix`,i.e. a sparse matrix in ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide `.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'ignore'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide `.",None
,"max_cate

In [27]:
enc.transform(y)

array([[1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

### The third row, containing B, has 0 for both dummies, A and C.

# Encoding extra features
### Consider that you have a ***feature X*** in ***dataset A***. This feature X only contains values ***[P, Q, R, S***]. Now suppose you fit your one hot encoder onto this particular feature X. However, you want to train it on the same feature X, but in ***dataset B***, which contains values ***[P, Q, R, S, T]***. Due to the presence of T, our encoder will raise an error.

### Thus, in such situations were we know that there are **extra dummy variables** which are **not** present in the feature we wish to **set** to, but which may be present in other features we want to **transform**, we use the **`categories=[]`** arguement.

In [37]:
x = [["A", "X"],
     ["B", "Y"],
     ["C", "Z"]]

In [40]:
enc = OneHotEncoder(sparse_output=False, categories=[["A", "B", "C", "D"], ["X", "Y", "Z"]])

#here, we are telling our encoder: 
#my dataset has two features.
#the first feature has values ["A, B, C, D"], and not all of them are guaranteed to be present.
#the second feature has values ["X, Y, Z"], and not all of them are guaranteed to be present.

In [41]:
enc.fit_transform(x)

array([[1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1.]])

### A column is created for D even though it does not appear in my array.

In [42]:
y = [["D", "Z"]]

In [43]:
enc.transform(y)

array([[0., 0., 0., 1., 0., 0., 1.]])