In [1]:
import pandas as pd
from get_path import get_path as gp

In [2]:
df = pd.read_csv(gp())

In [3]:
x = df.iloc[:, :3].dropna()

In [4]:
x.head()

,mean radius,mean texture,mean perimeter
1,20.57,17.77,132.90
2,19.69,21.25,130.00
3,11.42,20.38,77.58
5,12.45,15.70,82.57
7,13.71,20.83,90.20


# **Normalization**
### *Also known as 0-1 scaling*

In [5]:
from sklearn.preprocessing import MinMaxScaler

### **Values of a feature are scaled into a new feature, where the new minimum and maximum value are 0 and 1.**

In [6]:
scaler = MinMaxScaler()

In [7]:
(x_scaled := scaler.fit_transform(x))

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]], shape=(385, 3))

In [9]:
#checking max calue in each column

import numpy as np

np.apply_over_axes(np.max, x_scaled, axes=[0]) #function to apply, array to be applied on, axes to be applies on(0 => column, 1=> row)

array([[1., 1., 1.]])

In [10]:
np.apply_over_axes(np.min, x_scaled, axes=[0]) 

array([[0., 0., 0.]])

# **Standardization**
### Subtract mean and divide by standard deviation, to get "no. of standard deviations away from mean", => 0 mean, 1 std

In [11]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

(x_scaled := scaler.fit_transform(x))


array([[ 1.87149535, -0.35527432,  1.7252216 ],
       [ 1.61663638,  0.44774298,  1.6034021 ],
       [-0.77845877,  0.24698866, -0.59859036],
       ...,
       [ 2.1582117 ,  0.71080038,  2.10748279],
       [ 0.72173384,  2.02377982,  0.6918562 ],
       [ 1.88018373,  2.31221994,  2.02767001]], shape=(385, 3))

In [17]:
np.apply_over_axes(np.mean, x_scaled, axes=[0])

array([[-7.38226219e-17, -2.86062660e-16, -1.84556555e-17]])

In [19]:
np.apply_over_axes(np.var, x_scaled, axes=[0])

array([[1., 1., 1.]])

# **Robust Scaling**
### Subtract median(Resistant to outliers, hence, robust), and divide by IQR -> Inter quantile range, i.e., 75% percentile - 25% percentile

In [20]:
from sklearn.preprocessing import RobustScaler

In [23]:
scaler = RobustScaler()

(x_scaled := scaler.fit_transform(x))

array([[ 1.78484108, -0.18650089,  1.64689365],
       [ 1.56968215,  0.43161634,  1.54510355],
       [-0.45232274,  0.27708703, -0.29484029],
       ...,
       [ 2.02689487,  0.63410302,  1.96630397],
       [ 0.81418093,  1.64476021,  0.78343278],
       [ 1.79217604,  1.86678508,  1.8996139 ]], shape=(385, 3))

In [24]:
np.apply_over_axes(np.median, x_scaled, axes=[0])

array([[0., 0., 0.]])

### ***Note***: As these are linear transformations, unscaled datasets can be retrieved by using invers transformation methods which are built into the scaler objects. Simply use the scaler.inverse_transform(dataset) method.