In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

In [2]:
x, y = load_diabetes(return_X_y=True)

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    random_state = 11,
    test_size = 0.4
)

In [9]:
x_train, x_test

(array([[-0.02730979,  0.05068012, -0.00728377, ..., -0.03949338,
         -0.08237869, -0.02593034],
        [-0.02367725, -0.04464164, -0.06979687, ..., -0.03949338,
         -0.08913335, -0.05078298],
        [-0.00188202, -0.04464164, -0.06440781, ...,  0.03430886,
          0.01178548, -0.05492509],
        ...,
        [ 0.07076875, -0.04464164,  0.01211685, ..., -0.00259226,
          0.02539508, -0.0052198 ],
        [-0.00551455,  0.05068012, -0.04177375, ..., -0.03949338,
          0.01022672, -0.00936191],
        [-0.05273755,  0.05068012, -0.01159501, ...,  0.07120998,
          0.03056363, -0.0052198 ]], shape=(265, 10)),
 array([[-0.00188202, -0.04464164, -0.06656343, ..., -0.00259226,
         -0.02029232, -0.02593034],
        [ 0.02354575,  0.05068012, -0.03099563, ..., -0.00259226,
         -0.07409261, -0.03421455],
        [ 0.08893144, -0.04464164,  0.00672779, ..., -0.03949338,
          0.00943366,  0.03205916],
        ...,
        [ 0.04534098, -0.04464164, -0

In [10]:
model = LinearRegression()

In [11]:
model.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [12]:
model.predict(x_train)

array([ 72.49376753,  57.97768954, 127.34582955, 120.69462857,
       193.75410872, 162.01112793,  73.81458238, 177.90723661,
       227.36482722,  48.97302773, 115.64529439, 144.59114071,
       107.17861551, 126.15573898, 190.67228225, 100.65626293,
       137.00042944, 134.37448914, 204.80657331, 205.74423655,
       161.52082076, 161.09812087, 209.00264413,  47.79145123,
        69.48169002, 149.86692341, 143.78697694, 156.76667415,
       151.38818779, 152.74449972, 163.69292004, 149.47193996,
       107.35344782, 112.6286713 , 129.98402811, 130.15547576,
       167.5242823 , 211.03393228, 206.92592249, 229.62668314,
       162.60509132, 199.39281954, 105.1621536 , 117.69705481,
       135.77780521, 234.21013615, 202.41363458, 130.60617007,
        99.69864411,  98.12421712, 212.97695948,  59.56579051,
        94.12932121, 141.83225068, 158.17799933, 123.77417077,
       177.84937207, 149.7962592 , 190.46692489, 117.33289163,
       164.72200965,  77.73032465, 158.31290985,  82.07

In [14]:
model.predict(x_test)

array([109.15345132,  86.55507087, 161.50670488, 186.89536188,
        73.45668742, 236.9866512 ,  91.32048614, 250.93362464,
       178.8616775 ,  99.05130702, 163.11613691, 262.64911185,
        80.5783012 , 123.21071568,  63.87902455,  80.49446125,
        77.06471302, 153.10779526, 176.53628169,  99.93549019,
        50.2237573 , 187.70540809, 109.82382416,  53.72164918,
       183.70184111, 154.6360512 , 206.38319252, 176.26781889,
       251.38440688, 156.4292982 , 188.54565188, 153.40483206,
       166.87495277, 187.04373191, 132.23507278, 116.40483904,
        84.88710984, 176.85495737, 134.81843033, 165.68196823,
        82.12805115, 103.23635318, 197.71426571, 214.47274004,
       189.71637429, 155.57837973, 181.92277437, 153.98849919,
       264.52736348, 204.41299329, 172.81663866, 251.78508793,
       101.94717952, 100.15252894, 153.96832982, 120.31058191,
       215.6249597 , 133.57284208, 202.34156746, 122.48505576,
        74.11493779, 120.02003506, 164.16174161, 120.20

In [15]:
model.coef_

array([ -24.36087242, -202.26095607,  571.41278497,  336.44793603,
       -234.74937311,   32.01052754, -113.83016171,    8.73046724,
        541.16285718,   38.83461469])

In [16]:
model.intercept_

np.float64(150.27203835015473)