In [61]:
import torch
import numpy as np

In [62]:
data = [[1, 2],
        [3, 4]]

data_arr = np.array(data)

In [63]:
torch.tensor(data), torch.from_numpy(data_arr)

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [64]:
data = torch.tensor(data)

In [65]:
torch.ones_like(data)

tensor([[1, 1],
        [1, 1]])

In [66]:
torch.rand_like(data, dtype = torch.float)

tensor([[0.2642, 0.8500],
        [0.0936, 0.6489]])

In [67]:
shape = (4, 5)

In [68]:
torch.rand(shape), torch.ones(shape), torch.zeros(shape)

(tensor([[0.0691, 0.6502, 0.6704, 0.7255, 0.4138],
         [0.8955, 0.6466, 0.6776, 0.3028, 0.4289],
         [0.0275, 0.9344, 0.5362, 0.0341, 0.2454],
         [0.3009, 0.1413, 0.3762, 0.0958, 0.5938]]),
 tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]))

In [69]:
data.shape, data.device, data.dtype

(torch.Size([2, 2]), device(type='cpu'), torch.int64)

In [70]:
# setting an accelerator
if torch.accelerator.is_available():
    data = data.to(torch.accelerator.current_accelerator())

In [71]:
data = torch.ones((4, 4))

In [72]:
data[:, -1]

tensor([1., 1., 1., 1.])

In [73]:
data[:, 1] = 0

In [74]:
data

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [75]:
t1 = torch.rand((3, 6))
t2 = torch.rand(3, 5)

In [76]:
torch.cat((t1, t2), dim = 1)

tensor([[0.3203, 0.0492, 0.3786, 0.4675, 0.9784, 0.3066, 0.6889, 0.7211, 0.2354,
         0.4219, 0.2017],
        [0.8016, 0.4169, 0.8988, 0.4762, 0.2215, 0.4196, 0.9521, 0.7408, 0.7569,
         0.4292, 0.5909],
        [0.6286, 0.8079, 0.5539, 0.1819, 0.7916, 0.1055, 0.9135, 0.0790, 0.1204,
         0.5961, 0.5379]])

In [77]:
data = torch.rand((4, 4))
y1 = data @ data.T
y2 = torch.matmul(data, data.T)

y3 = torch.rand_like(y1)

z1 = data * data.T
z2 = torch.mul(data, data.T)

z3 = torch.rand_like(y1)

In [78]:
torch.matmul(data, data.T, out = y3), torch.mul(data, data.T, out = z3)

(tensor([[1.2809, 1.4130, 0.6663, 1.2834],
         [1.4130, 1.7055, 0.8570, 1.4399],
         [0.6663, 0.8570, 0.4733, 0.6339],
         [1.2834, 1.4399, 0.6339, 1.4492]]),
 tensor([[0.3458, 0.5325, 0.1035, 0.2580],
         [0.5325, 0.5282, 0.1740, 0.3461],
         [0.1035, 0.1740, 0.0311, 0.3400],
         [0.2580, 0.3461, 0.3400, 0.0949]]))

In [79]:
agg = data.sum()
agg_item = agg.item()
agg_item, type(agg_item)

(8.29960823059082, float)

In [80]:
data.t_() # saves memory but can cause problems in getting grad cus history loss

tensor([[0.5881, 0.6897, 0.2127, 0.8069],
        [0.7721, 0.7268, 0.3823, 0.4922],
        [0.4865, 0.4552, 0.1765, 0.6789],
        [0.3198, 0.7032, 0.5008, 0.3081]])

In [81]:
t = torch.ones(5)
n = t.numpy()

t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [82]:
t.add_(1)

t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))