In [1]:
import numpy as np

# NumPy Quick Tutorial


# 1. Creating Arrays
print("=== Creating Arrays ===")
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D array: {arr1}")

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D array:\n{arr2}")

zeros = np.zeros((2, 3))
print(f"Zeros array:\n{zeros}")

ones = np.ones((2, 3))
print(f"Ones array:\n{ones}")

range_arr = np.arange(0, 10, 2)
print(f"Range array: {range_arr}")

# 2. Array Operations
print("\n=== Array Operations ===")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")
print(f"Element-wise power: {a ** 2}")

# 3. Array Indexing and Slicing
print("\n=== Indexing and Slicing ===")
arr = np.arange(10)
print(f"Array: {arr}")
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")
print(f"Slice [2:5]: {arr[2:5]}")

# 4. Array Shape and Reshape
print("\n=== Shape and Reshape ===")
arr = np.arange(12)
print(f"Original shape: {arr.shape}")
reshaped = arr.reshape(3, 4)
print(f"Reshaped to (3,4):\n{reshaped}")

# 5. Basic Statistics
print("\n=== Statistics ===")
arr = np.array([1, 2, 3, 4, 5])
print(f"Mean: {np.mean(arr)}")
print(f"Std Dev: {np.std(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Sum: {np.sum(arr)}")

=== Creating Arrays ===
1D array: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]
Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]
Range array: [0 2 4 6 8]

=== Array Operations ===
Addition: [5 7 9]
Multiplication: [ 4 10 18]
Element-wise power: [1 4 9]

=== Indexing and Slicing ===
Array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Slice [2:5]: [2 3 4]

=== Shape and Reshape ===
Original shape: (12,)
Reshaped to (3,4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

=== Statistics ===
Mean: 3.0
Std Dev: 1.4142135623730951
Max: 5
Sum: 15
